[package]
name = "http-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
clap = { version = "3.2.20", features = ["derive"] }
color-eyre = "0.6"
dotenv = "0.15.0"
eyre = "0.6.1"
futures = "0.3.24"
http = "0.2.8"
hyper = { version = "0.14.20", features = ["client", "server", "stream"] }
hyper-rustls = { version = "0.23.0", features = ["http2"] }
redis = { version = "0.21.6", features = [ "aio", "connection-manager", "tokio-comp" ] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4.13", features = ["make"] }
tower-http = "0.3.4"
tracing = "0.1.36"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }